name: CI
on:
  push:
  pull_request:

jobs:
  run-pipelines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        case: [main, io]
    steps:
      - uses: actions/checkout@v4

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y gfortran

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install numpy matplotlib

      - name: Build & run & plot
        run: |
          make -j2 ${{ matrix.case }}

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.case }}-results
          path: |
            results/**
            !results/.gitkeep
          if-no-files-found: ignore

